---
title: "Figure 1"
date: today
date-format: "D MMM YYYY"
format:
  html:
    embed-resources: true
    toc: true
    toc-depth: 2
    highlight-style: github
    code-tools:
      source: true
      toggle: true
---

## 1. Libraries and global settings

```{r libraries}
#| code-fold: true
#| output: false
#| warning: false
#| message: false
library(MOFA2)
library(tidyverse)

library(png)
library(grid)
library(patchwork)
library(cowplot)

# setwd("/Users/vilkal/work/Brolidens_work/Projects/Candida-omics/manuscript")

select <- dplyr::select
map <- purrr::map
rename <- dplyr::rename
```


```{r load-data}
# meta data
comb_meta_path <- "../Results/Combined_gr_meta_data.csv"
meta <- read_csv(comb_meta_path) %>%
  #rename(sample = "svamp_ID") %>%
  mutate(across(2:27, ~ factor(.x)))

# scematic figure
img_path <- "../resources/Scematic_figure.png"
img <- readPNG(img_path)
```

```{r plot-scematic-figure}
g <- rasterGrob(img, interpolate = TRUE) #, height = 1, width = 1

# quartz(width = 6, height = 2)
g
```


## 2. Load trained MOFA model
We load the model with the highest elbo score
```{r load-MOFA-model}
#| eval: true
#| include: true
#| warning: false
#| message: false
#| tbl-colwidths: [60,40]
elbo_table <- read_csv("../Results/MOFA/elbo_table_noS84_1e-6_57MG.csv")
knitr::kable(elbo_table)
best_seed <- elbo_table$seed[which.max(abs(elbo_table$elbo))]

MOFAmodel <- load_model(
  paste0("../Results/MOFA/MOFA_allBL_noS84_1e-6_57MG_seed_", best_seed, ".hdf5")
)

# add meta data to model
samples_metadata(MOFAmodel) <- samples_metadata(MOFAmodel)[, c(
  "sample",
  "group"
)] %>%
  left_join(meta, by = c("sample"))
```

```{r model-overview}
#| fig-width: 6
#| fig-height: 3
# inspect the model:
ovw <- plot_data_overview(MOFAmodel) +
  #theme_bw(base_size = 15 / .pt) +
  theme(
    plot.margin = unit(c(-0.2, -0.2, 0.1, 0.1), "cm"),
    axis.text.y = element_text(color = "#636363"),
    text = element_text(size = 7)
  ) + #  #EC645A, #CD3B8E, #994E95
  scale_fill_manual(
    values = c("#CC79A7", "#D55E00", "#CD3B8E", "gray", "#E69F00"),
    na.value = "gray"
  )
# quartz(width = 2, height = 2, dpi = 150)
ovw
```

## 3. Plot variance explained

```{r variance-explained}
#| warning: false
#| message: false
#| fig-width: 9.5
#| fig-height: 3
p1 <- plot_variance_explained(MOFAmodel, plot_total = TRUE)[[2]]
p2 <- plot_variance_explained(MOFAmodel, factors = 1:9)

#+
#theme(axis.text.x = element_text(angle = 45, hjust = 0.8, vjust = 0.9))
# plot_grid(plotlist = list(p1, p2), ncol = 2)

p1$layers[[1]]$aes_params$fill <- "gray" # remove fixed fill
p1$layers[[1]]$aes_params$colour <- "white" # remove fixed fill #717272

p2$layers[[1]]$aes_params$linewidth <- 0.1

p1 <- p1 +
  coord_flip() +
  theme(
    text = element_text(size = 7),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.line.x = element_line(linewidth = 0.2, colour = "#636363"),
    axis.line.y = element_blank(),
    plot.margin = unit(c(0, 0.1, 0, -0.3), "cm")
  )
p2 <- p2 +
  coord_flip() +
  guides(fill = guide_colorbar(title = "", barwidth = 7, barheight = 0.3)) +
  theme(
    text = element_text(size = 7),
    legend.position = c(0.5, 1.09), # 👈 just above panel, tight
    legend.direction = "horizontal",
    legend.text = element_text(size = 6),
    legend.title = element_text(size = 6),
    legend.text.position = "top",
    legend.margin = margin(0, 0, -0, 0), # moves the legend box
    legend.box.margin = margin(-0, 0, -0, -0.3)
  ) + # moves the legend) +
  theme(axis.text.y = element_blank()) +
  theme(plot.margin = unit(c(0, 0, 0, -0.3), "cm")) +
  scale_y_discrete(labels = 1:10) +
  scale_fill_gradientn(
    colors = c("gray97", "darkblue"),
    labels = scales::label_number(suffix = "%") # 👈 THIS is the key
  )

# quartz(width = 6, height = 2)
B <- plot_grid(plotlist = list(ovw, p2, p1), nrow = 1, align = c("h"))
B
# p$layers[[1]]$aes_params$alpha
```

## 4. Varance explained stats

```{r get-variance-df}
ve_df <- get_variance_explained(MOFAmodel)$r2_per_factor$single_group %>%
  as.data.frame() %>%
  rownames_to_column("Factor") %>%
  pivot_longer(
    -Factor,
    names_to = "view",
    values_to = "variance_explained"
  ) %>%
  mutate(Factor = factor(.$Factor, levels = paste0("Factor", 1:15)))
```

```{r variance-stats}
# summarized by view for Factor 1-10:
ve_df %>%
  filter(grepl("^Factor[1-9]$|^10$", .$Factor)) %>%
  summarize(sum = sum(variance_explained), .by = c("view")) %>%
  add_case(., view = "Total", sum = sum(.$sum)) %>%
  knitr::kable(., digits = 2)

# Factors with <2% in all views
ve_df %>%
  summarise(all_below_2 = all(variance_explained < 2), .by = c("Factor")) %>%
  filter(all_below_2) %>%
  knitr::kable(., digits = 2)

# summarized by view for Factor 1:
ve_df %>%
  filter(grepl("^Factor1$", .$Factor)) %>%
  #filter(grepl("^Factor[1-9]$", .$Factor)) %>%
  summarize(sum = sum(variance_explained), .by = c("Factor", "view")) %>%
  knitr::kable(., digits = 2)

# Sum variance per factor:
ve_df %>%
  #filter(grepl("^Factor[1-9]$", .$Factor)) %>%
  summarize(sum = sum(variance_explained), .by = c("Factor")) %>%
  knitr::kable(., digits = 2)
```

## 5. Final combined plot

```{r combine-plots}
#| fig.width: 5.5
#| fig.height: 4
#############################
# COMBINE ALL FIGURE PANELS #
#############################
# quartz(width = 5.5, height = 4, dpi = 150)
Figure1 <- plot_grid(
  g,
  B,
  ncol = 1,
  rel_heights = c(1, 1),
  labels = c('A', 'B')
)
ggsave(
  "./Figures/Figure1.pdf",
  Figure1,
  width = 5.5,
  height = 4,
  bg = "white",
  dpi = 1000
)

Figure1
```