---
title: "Figure 5"
date: today
date-format: "D MMM YYYY"
format:
  html:
    embed-resources: true
    toc: true
    toc-depth: 2
    highlight-style: github
    code-tools:
      source: true
      toggle: true
---
## 1. Libraries and global settings

```{r libraries}
#| code-fold: true
#| output: false
#| warning: false
#| message: false
library(MOFA2)
library(tidyverse)
library(readxl)

library(cowplot)
library(RColorBrewer)
library(ggh4x)

# setwd("/Users/vilkal/work/Brolidens_work/Projects/Candida-omics/manuscript")

select <- dplyr::select
map <- purrr::map
rename <- dplyr::rename
```


```{r load-data}
#| output: false
#| warning: false
#| message: false
# meta data
m <- read_csv("../Results/Sample_omic_table.csv")
comb_meta_path <- "../Results/Combined_gr_meta_data.csv"
meta <- read_csv(comb_meta_path) %>%
  #rename(sample = "svamp_ID") %>%
  mutate(across(2:27, ~ factor(.x)))

# omic data
comb_relative_long <- read_csv(
  "../Tidy_data/Metagenomics/Functional/Functional_abundance_CLR_filtered_long.csv"
)
TRX_path <- "../Results/MixOmic/Transcriptomics_batch_filt.csv"
TRX_batch <- read.csv(TRX_path, row.names = 1)

MB_path <- "../Results/MixOmic/Metabolom_Normalized.csv"
#MB_path <- "../Results/MixOmic/Metabolom_Normalized_all.csv"
MB_matrix <- read_csv(MB_path)

# omic colour pallet
MG_hirarchy <- read_csv("../Results/Metagenomics/Metagenome_col_pal.csv")
FM_colours <- read_csv("../Results/Metagenomics/Functional_col_pal.csv")
MB_colours <- read_csv("../Results/Metagenomics/Metabolome_col_pal.csv")
```

```{r line-break-function}
insert_line_break <- function(x, min_length = 15) {
  purrr::map_chr(x, \(xi) {
    if (nchar(xi) <= min_length) {
      return(xi)
    }
    sp <- stringr::str_locate_all(xi, " ")[[1]][, 1]
    if (!length(sp)) {
      return(xi)
    }
    i <- sp[which.min(abs(sp - nchar(xi) / 2))]
    paste0(substr(xi, 1, i - 1), "\n", substr(xi, i + 1, nchar(xi)))
  })
}
```

```{r pallets}
#| code-fold: true
# colour pallet

MB_colours <- set_names(MB_colours$col, MB_colours$Pathway)
# FM_colours <- set_names(FM_colours$col, FM_colours$Pathway)
FM_colours <- set_names(FM_colours$col, insert_line_break(FM_colours$Pathway))

gene_col <- c(
  "#B71E42FF",
  "#DE478E",
  "#BC72F0FF",
  "#795FAFFF",
  "#D53DD0",
  "#EA6312",
  "#FFAE34FF",
  "#EF6F6AFF",
  "#8CC2CAFF",
  "#6388B4FF"
)
pal <- list(
  "Clinical_score_(0-5)" = brewer.pal(6, name = "Reds"),
  RVVC_pos = c("#A6CEE3", "#1F78B4", "#e490c4ff", "#c12d88ff"),
  fct1_clus = c("#33A02C", "#B2DF8A", "#FF7F00", "#FDBF6F"),
  RVVC_pos = c("#A6CEE3", "#1F78B4", "#e490c4ff", "#c12d88ff"),
  treatment = c("#FFAE34FF", "#8CC2CAFF", "#EF6F6AFF"),
  "Clinical score (0-5)" = brewer.pal(6, name = "Reds"),
  CST = c(
    "I" = "#148F77",
    "II" = "#6d9f06",
    "III" = "#A3E4D7",
    "IV-B" = "#E794C1",
    "IV-C" = "#b5cb8c",
    "V" = "#43BA8F"
  )
)

# default ggplot2 pallet:
gg_color_hue <- function(n) {
  hues <- seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}
gg_color_hue(4)

tax_pallet <- c(brewer.pal(12, "Set3"), brewer.pal(8, "Dark2"))
other <- c(
  "#E3E6AD",
  "#F8D0A4",
  "#c4ce96",
  "#9aacce",
  "#e1caff",
  "#abc5bf",
  "#ffffd4",
  "#c0a2c1",
  "#c8ffd5",
  "#c8ffd5",
  "#afb7ee",
  "#ffc8d9",
  "#ffc8d9",
  "#e7b993",
  "#c8ffd5",
  "#c4cea9",
  "#a1b37d",
  "#a6cca7",
  "#d1b9ee",
  "#88c29c",
  "#fdcc8a",
  "#91c6f7",
  "#f5f8bd",
  "#8db1c5",
  "#fab0aa",
  "#7cb6b6",
  "#96f3eb",
  "#6ececc"
)
```

## 2. Load trained MOFA model
We load the model with the highest elbo score

```{r load-MOFA-model}
#| eval: true
#| include: true
#| warning: false
#| message: false
#| tbl-colwidths: [60,40]
elbo_table <- read_csv("../Results/MOFA/elbo_table_noS84_1e-6_57MG.csv")
knitr::kable(elbo_table)
best_seed <- elbo_table$seed[which.max(abs(elbo_table$elbo))]

MOFAmodel <- load_model(
  paste0("../Results/MOFA/MOFA_allBL_noS84_1e-6_57MG_seed_", best_seed, ".hdf5")
)

# add meta data to model
samples_metadata(MOFAmodel) <- samples_metadata(MOFAmodel)[, c(
  "sample",
  "group"
)] %>%
  left_join(meta, by = c("sample"))
```

## 3. Clean up pathway column
```{r clean-columns}
m <- read_csv("../Results/Sample_omic_table.csv")
s <- m$sample[m$at_least_two & m$all_BL]

comb_long <- comb_relative_long %>%
  separate(col = "Pathway", sep = "\\|", into = c("Pathway", "taxa")) %>%
  separate(col = "Pathway", sep = ": ", into = c("short", "long")) %>%
  mutate(taxa = ifelse(is.na(taxa), "total", taxa)) %>%
  mutate(taxa = gsub("^.+s__", "", .$taxa)) %>%

  mutate(taxa = ifelse(is.na(taxa), "unintegrated", taxa)) %>%
  mutate(species = str_replace_all(taxa, "_", " ")) %>%
  mutate(genus = str_replace(taxa, "_\\w+$", "")) %>%
  left_join(
    .,
    select(meta, 1:6, fct1_clus, `Clinical_score_(0-5)`, CST),
    by = c("sample")
  ) %>%
  # filter samples:
  filter(sample %in% s) %>%
  filter(sample != "S10") %>%
  split(~level)
```

## 4. Get 20 top pathways

```{r weights}
library(MOFA2)
weights <- get_weights(MOFAmodel, factors = 1, as.data.frame = T) %>%
  as_tibble() %>%
  mutate(feature = as.vector(.$feature)) %>%
  group_by(view) %>%
  arrange(desc(abs(value))) %>%
  split(~view)

weights$Metagenomics <- weights$Metagenomics %>%
  arrange(desc(abs(value))) %>%
  mutate(feature = str_replace(feature, "_", " "))
```

```{r plot-weights-function}
plot_top_weights_tidy <- function(
  weights_df,
  facet = "view", # "factor" or "view"
  nfeatures = 10,
  fact = 1,
  scale = TRUE,
  abs = TRUE,
  sign = "all"
) {
  # Remove zeros
  W <- weights_df %>% filter(weight != 0)

  W <- W %>%
    filter(grepl(paste0("^Factor", fact, "$", collapse = "|"), .$factor))

  if (scale) {
    W <- W %>%
      group_by(.data[[facet]]) %>%
      mutate(weight = weight / max(abs(weight)))
  }

  # Sign
  W <- W %>%
    mutate(sign_label = if_else(weight > 0, "+", "-"))

  if (sign == "positive") {
    W <- W %>% filter(weight > 0)
  } else if (sign == "negative") {
    W <- W %>% filter(weight < 0)
  }

  if (abs) {
    W <- W %>% mutate(weight = abs(weight))
  }

  # Select top genes per factor
  W <- W %>%
    group_by(.data[[facet]]) %>%
    slice_max(order_by = weight, n = nfeatures) %>%
    #arrange(weight) %>%
    #fct_reorder(genes, weight) %>%
    #mutate(genes_id = factor(genes)) %>%
    ungroup()

  # Factor ordering
  W <- W %>%
    arrange(factor, weight) %>%
    mutate(genes_id = factor(genes, levels = unique(genes)))
  #mutate(genes_id = factor(genes, levels = rev(unique(genes))))

  # Plot
  p <- ggplot(W, aes(x = genes_id, y = weight, color = sign_label)) + # , color = clus
    geom_point(size = 2) +
    geom_segment(
      aes(xend = genes_id, yend = 0),
      linewidth = 0.75,
      show.legend = F
    ) +
    #scale_colour_manual(values = pal2[["gene_clus"]], na.value = "gray") +
    scale_colour_manual(values = c("#6388B4FF", "#EF6F6AFF")) +
    coord_flip() +
    labs(y = "Weight", x = NULL) +
    theme_bw() +
    theme(
      axis.text.y = element_text(size = rel(1.1)),
      panel.grid.major.y = element_blank(),
      legend.position = "none"
    ) +
    facet_wrap(as.formula(paste("~", facet)), ncol = 2, scales = "free")

  if (abs) {
    p <- p +
      ylim(0, max(W$weight) + 0.1) +
      geom_text(
        aes(label = sign_label),
        y = max(W$weight) + 0.1,
        size = 4,
        show.legend = F
      )
  }

  return(p)
}
```

```{r get-weights}
#| fig.width: 13
#| fig.height: 8
# quartz(width = 13, height = 8)
lvl <- c("Transcriptomics", "Functional", "Metabolomics", "Metagenomics")
# my function
get_weights(
  MOFAmodel,
  as.data.frame = TRUE,
) %>%
  as_tibble() %>%
  rename(genes = "feature", weight = "value") %>%
  filter(factor == "Factor1") %>%
  mutate(view = factor(.$view, levels = lvl)) %>%
  plot_top_weights_tidy(., facet = "view", nfeatures = 15)
```

## 5. Plot all candida expressed pathways

```{r plot-candida-pathways}
#| fig.width: 8.5
#| fig.height: 6
top <- weights$Functional$feature[1:20]
# col <- brewer.pal(8, name = "Purples")
col <- c(
  "#f9f9f9",
  "#DADAEB",
  "#BCBDDC",
  "#9E9AC8",
  "#807DBA",
  "#6A51A3",
  "#54278F",
  "#3F007D"
)

pat_Candida <- comb_long$taxa_lvl %>%
  filter(short != "UNINTEGRATED") %>%
  filter(grepl("Candida", .$taxa)) %>%
  pull(., "long") %>%
  unique()

pat_Candida

# plot pathways expressed by candida
var <- "RVVC_pos"
var <- "fct1_clus"
df_sum_CLR_candida <- comb_long$taxa_lvl %>%
  filter(short != "UNINTEGRATED") %>%
  filter(long %in% pat_Candida) %>%
  mutate(Candida = ifelse(grepl("Candida", .$taxa), "Candida", "other")) %>%

  #mutate(groups = factor(.$Clusters, levels=names(clus_lvl))) %>%
  group_by(short, long, .data[[var]], Candida) %>%
  filter(!(is.na(CLR))) %>%
  summarise(
    Avg = mean(CLR),
    Avg_ = mean(CLR) / max(CLR), # gives the median as a percentage of max value among spots if .5 you have a normal dist.
    Pct = sum(CLR > 0) / length(CLR) * 100,
    .groups = "drop"
  ) %>%
  #group_by(marker) %>%
  #nest()
  mutate(Avg_p = Avg / max(Avg), .by = "short") #%>%
#split(~Candida)

# quartz(width = 7, height = 6) # , dpi = 150
df_sum_CLR_candida %>%
  ggplot(., aes(y = long, x = .data[[var]])) +
  geom_point(aes(size = Pct, fill = Avg), col = "gray", shape = 21) + #"#6A2595"
  # scale_fill_gradientn(
  #   colours = rev(RColorBrewer::brewer.pal(11, "RdBu")),
  #   name = "Average\nCLR"
  # ) +
  scale_fill_gradient2(
    low = "#2166ac",
    mid = "white",
    high = "#b2182b",
    midpoint = 0,
    name = "Average\nexpression"
  ) +
  theme_minimal() +
  theme(
    axis.title = element_blank(),
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) +
  facet_wrap(~Candida)
```

```{r top-pathways}
#| fig.width: 8.5
#| fig.height: 6
# plot top pathways
var <- "RVVC_pos"
var <- "fct1_clus"
df_sum_CLR <- comb_long %>%
  bind_rows(.id = "level") %>%
  filter(short != "UNINTEGRATED") %>%
  filter(long %in% top) %>%
  mutate(long = insert_line_break(long)) %>%
  mutate(L.iners = ifelse(grepl("iners", .$taxa), "L.iners", "other")) %>%

  #mutate(groups = factor(.$Clusters, levels=names(clus_lvl))) %>%
  group_by(short, long, .data[[var]], level) %>%
  filter(!(is.na(CLR))) %>%
  summarise(
    Avg = mean(CLR),
    Avg_ = mean(CLR) / max(CLR), # gives the median as a percentage of max value among spots if .5 you have a normal dist.
    Pct = sum(CLR > 0) / length(CLR) * 100,
    .groups = "drop"
  ) %>%
  #group_by(marker) %>%
  #nest()
  mutate(Avg_p = Avg / max(Avg), .by = "short") #%>%
#split(~L.iners)

pathway_order <- df_sum_CLR %>%
  filter(level == "community_lvl") %>%
  filter(.data[[var]] %in% c(1, 4)) %>%
  select(long, group = all_of(var), Avg) %>%
  pivot_wider(
    names_from = group,
    values_from = Avg
  ) %>%
  mutate(diff = `4` - `1`) %>%
  mutate(regulation = if_else(diff > 0, "Down", "Up")) %>%
  #arrange(`4`)
  arrange(desc(diff)) # or arrange(desc(diff))

# quartz(width = 7, height = 6) # , dpi = 150
df_sum_CLR %>%
  mutate(long = factor(long, levels = pathway_order$long)) %>%
  left_join(., select(pathway_order, long, diff, regulation), by = "long") %>%
  mutate(regulation = factor(.$regulation, levels = c("Up", "Down"))) %>%
  ggplot(., aes(y = long, x = .data[[var]])) +
  geom_point(aes(size = Pct, fill = Avg), col = "gray", shape = 21) + #"#6A2595"
  # scale_fill_gradientn(
  #   colours = col,
  #   guide = guide_colorbar(ticks.colour = "black", frame.colour = "white"),
  #   name = "Average\nexpression"
  # ) +
  scale_fill_gradientn(
    colours = rev(RColorBrewer::brewer.pal(11, "RdBu")),
    name = "Average\nCLR"
  ) +
  theme_minimal() +
  theme(
    axis.title = element_blank(),
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) +
  facet_grid(
    cols = vars(level),
    rows = vars(regulation),
    space = "free",
    scales = "free"
  )
```

## 6. Plot top 20 pathways by RVVCpos groups
Only 12 out of the 20 pathways were in the taxa lecel dataset
```{r plot-top-20-pathways-by-RVVCpos}
# NB! 8/20 of the top pathways were not present in the taxa level dataset
setdiff(top, comb_long$taxa_lvl$long)

comb_long$taxa_lvl %>%
  filter(long %in% top) %>%
  mutate(long = insert_line_break(long)) %>%
  ggplot(., aes(y = CLR, x = .data[["RVVC_pos"]])) +
  geom_point(aes(fill = CLR), col = "gray", shape = 21) +
  facet_wrap(~long) +
  theme_minimal() +
  theme(
    axis.title = element_blank(),
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
```

## 7. Plot selected pathways from Candida

```{r top-candida-pathways}
#| fig.width: 9
#| fig.height: 4
pat <- c(
  "glycolysis IV",
  "adenosine deoxyribonucleotides de novo biosynthesis II",
  "inosine-5'-phosphate biosynthesis II",
  "superpathway of guanosine nucleotides de novo biosynthesis I",
  "chorismate biosynthesis I",
  "superpathway of aromatic amino acid biosynthesis",
  "cis-vaccenate biosynthesis"
)

fill_val <- "Clinical_score_(0-5)"
fill_val <- "RVVC_pos"

# quartz(width = 9, height = 4, dpi = 100)
comb_long$taxa_lvl %>%
  filter(short != "UNINTEGRATED") %>%
  filter(grepl("Candida", .$taxa)) %>%
  filter(long %in% pat) %>%

  mutate(long = insert_line_break(long)) %>%
  arrange(`Clinical_score_(0-5)`) %>%
  #filter(long == "glycolysis IV") %>%
  ggplot(., aes(y = CLR, x = .data[["fct1_clus"]])) +
  geom_jitter(
    aes(fill = .data[[fill_val]]),
    col = "gray",
    shape = 21,
    width = 0.3
  ) +
  scale_fill_manual(values = pal[[fill_val]]) +
  theme_minimal() +
  facet_wrap(~long, nrow = 2)
```

```{r top-path-by-CST}
#| fig.width: 7.3
#| fig.height: 8.5
fill_val <- "CST"
pat <- "inosine-5'-phosphate biosynthesis I"
# quartz(width = 9, height = 8, dpi = 100)
comb_long$community_lvl %>%
  filter(short != "UNINTEGRATED") %>%
  # filter(grepl("Candida", .$taxa)) %>%
  filter(long %in% top) %>%

  mutate(long = insert_line_break(long)) %>%
  arrange(`Clinical_score_(0-5)`) %>%
  #filter(long == "glycolysis IV") %>%
  ggplot(., aes(y = CLR, x = .data[["fct1_clus"]])) +
  geom_jitter(
    aes(fill = .data[[fill_val]]),
    col = "gray",
    shape = 21,
    width = 0.3
  ) +
  scale_fill_manual(values = pal[[fill_val]]) +
  theme_minimal() +
  facet_wrap(~long, nrow = 4)
```

## 8. Plot taxa contribution for top pathways

```{r barplot-function}
#| code-fold: true
# ============================================================
# FUNCTION: Facet_bar.fun()
# ============================================================
# Description:
# Creates a faceted stacked bar plot using ggplot2, where
# samples are displayed on the x-axis and abundance values
# are stacked according to a specified grouping variable.
# NB! position = "fill", scales each bar to have the same height (100%)
#
# The plot is further divided into facets based on a user-
# defined variable, allowing comparison of compositional
# patterns across experimental groups or conditions.
#
# Workflow:
# 1. Map x-axis, y-axis, and fill aesthetics from input data
# 2. Generate stacked bar plot of abundance values
# 3. Apply minimal theme for clean visualization
# 4. Remove plot expansion to avoid extra spacing
# 5. Apply manual color scale for fill categories
# 6. Customize theme elements (axes, margins, legend)
# 7. Rotate and format x-axis labels for readability
# 8. Remove axis titles for cleaner faceted output
# 9. Facet plot by a user-defined variable with free x-scale
#    and free x-space for independent panel scaling
#
# Arguments:
# df :
#   Data frame containing plotting data.
#
#   Required columns:
#     - abundance : numeric values representing feature abundance
#     - grouping variable specified in `fill`
#     - grouping variable specified in `x_axis`
#
# facet_var :
#   Variable used to define faceting structure.
#   Supports tidy evaluation ({{ }}), typically categorical.
#
# fill :
#   Character string specifying the column used for fill
#   aesthetics (default: "annot").
#
# colours :
#   Named vector of colors used in scale_fill_manual().
#   Names must match levels of the fill variable.
#
# x_axis :
#   Character string specifying the x-axis variable
#   (default: "sample").
#
# Returns:
#   A ggplot object representing a faceted stacked bar plot.
#
# Plot characteristics:
#   - Stacked bar plot (position = "stack")
#   - Faceted by `facet_var` with free x-scales
#   - Minimal theme with customized axis and strip styling
#   - Legend removed for cleaner multi-panel visualization
#
# Side effects:
#   None
#
# Dependencies:
#   ggplot2
#   rlang (for {{ }} tidy evaluation)
#   grid (for unit())
# ============================================================

Facet_bar.fun <- function(
  df,
  facet_cols = NULL,
  facet_rows = NULL,
  fill = "pathway",
  colours,
  x_axis = "sample",
  annot_col = NULL, #"Clinical score (0-5)",
  strip_colours = NULL,
  legend = "none"
) {
  # -------------------------------
  # Apply strip colours if provided
  # -------------------------------
  # Only colour strips in x-direction
  if (!is.null(strip_colours)) {
    strip <- facet_grid2(
      cols = if (is.null(facet_cols)) NULL else vars(.data[[facet_cols]]),
      rows = if (is.null(facet_rows)) NULL else vars(.data[[facet_rows]]),
      scales = "free_x",
      space = "free_x",
      strip = strip_themed(background_x = elem_list_rect(fill = strip_colours))
    )
  } else {
    strip <- facet_grid(
      cols = if (is.null(facet_cols)) NULL else vars(.data[[facet_cols]]),
      rows = if (is.null(facet_rows)) NULL else vars(.data[[facet_rows]]),
      scales = "free_x",
      space = "free_x"
    )
  }

  # -------------------------------
  #  Annotation above barplot
  # -------------------------------
  library(ggnewscale)
  if (!is.null(annot_col)) {
    annot <- list(
      new_scale_fill(),
      geom_tile(
        aes(x = sample, y = 1.01, fill = .data[[annot_col]]),
        inherit.aes = FALSE,
        show.legend = F,
        height = 0.015, #width = 0.9
      ),
      scale_fill_manual(values = pal[[annot_col]], name = NULL),
      guides(
        fill = guide_legend(
          override.aes = list(size = 2),
          ncol = 1,
          byrow = T,
          keyheight = .4,
          keywidth = .6
        )
      )
    )
  } else {
    annot <- NULL
  }

  p <- ggplot(
    df,
    aes(fill = .data[[fill]], y = abundance, x = .data[[x_axis]])
  ) +
    geom_bar(position = "fill", stat = "identity") +
    theme_minimal(base_size = 8) +
    coord_cartesian(expand = FALSE) +
    scale_fill_manual(values = colours, name = NULL) +
    scale_y_continuous(labels = scales::label_percent(scale = 100)) +
    guides(
      fill = guide_legend(
        override.aes = list(size = 2),
        #ncol = 4, byrow = FALSE,
        keyheight = .4,
        keywidth = .6
      )
    ) +
    theme(
      strip.background = element_rect(colour = "gray", fill = NA),
      panel.border = element_rect(colour = "gray", fill = NA),
      plot.margin = unit(c(0.1, 0, 0.2, 0), "cm"),
      axis.text.x = element_blank(),
      #axis.text.x = element_text(angle = 90, hjust =1,  vjust = 0.5),
      #strip.text = element_text(lineheight = 0.5),
      strip.text.x = element_text(margin = margin(0.1, 0, 0.1, 0, "cm")),
      # axis.text.x = element_text(
      #   angle = 90,
      #   vjust = 0.5,
      #   hjust = 1,
      #   size = 8,
      #   margin = margin(t = -5, b = 3)
      # ),
      axis.title.y = element_blank(),
      axis.title.x = element_blank(),
      legend.spacing.y = unit(.1, 'cm'),
      legend.box.spacing = unit(.1, 'cm'),
      legend.key.spacing.y = unit(.1, 'cm'),
      legend.text = element_text(
        size = 8,
        margin = margin(r = 0.3, l = 0.3, unit = "pt"),
      ),
      legend.position = legend
    ) +
    strip +
    annot
}

add_CLR <- function(p, data, x, clr = "CLR") {
  clr_df <- data %>%
    summarise(
      CLR = mean(.data[[clr]], na.rm = TRUE),
      .by = c(all_of(x), "long")
    )

  p +
    ggnewscale::new_scale_fill() +
    geom_tile(
      data = clr_df,
      col = "gray",
      linewidth = 0.2,
      aes(x = .data[[x]], y = -0.15, fill = CLR),
      inherit.aes = FALSE,
      height = 0.2
    ) +
    guides(
      fill = guide_colourbar(
        barwidth = .5,
        barheight = 5,
        direction = "vertical",
        title.position = "top",
      )
    ) +
    scale_fill_gradient2(
      low = "#2166ac",
      mid = "white",
      high = "#b2182b",
      midpoint = 0,
      name = "Mean CLR"
    ) +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      #panel.border = element_blank(),
      axis.line = element_blank(),
      panel.background = element_blank(),
      plot.background = element_blank()
    ) +
    scale_x_continuous(expand = c(0, 0))
  #coord_cartesian(ylim = c(-0.04, 1), clip = "off")
}
```

```{r sample-order}
#| code-fold: true
sample_order <- c(
  "S28",
  "S45",
  "S12",
  "S40",
  "S33",
  "S72_BL",
  "S22",
  "S36",
  "S42",
  "S66_BL",
  "S51",
  "S03",
  "S73_BL",
  "S74_BL",
  "S55",
  "S82_BL",
  "S54",
  "S37",
  "S53",
  "S41",
  "S02",
  "S11",
  "S81_BL",
  "S01",
  "S61",
  "S04",
  "S07",
  "S06",
  "S90_BL",
  "S18",
  "S05",
  "S88_BL",
  "S76_BL",
  "S09",
  "S48",
  "S23",
  "S91_BL",
  "S57",
  "S25",
  "S50",
  "S30",
  "S15",
  "S68_BL",
  "S21",
  "S59",
  "S49",
  "S47",
  "S43",
  "S32",
  "S52",
  "S29",
  "S78_BL",
  "S34",
  "S31",
  "S70_BL",
  "S79_BL",
  "S27",
  "S67_BL",
  "S56",
  "S08",
  "S75_BL",
  "S63_BL",
  "S80_BL",
  "S89_BL",
  "S46",
  "S26",
  "S77_BL",
  "S19",
  "S83_BL",
  "S13",
  "S65_BL",
  "S87_BL",
  "S85_BL",
  "S64_BL",
  "S86_BL",
  "S58",
  "S71_BL",
  "S69_BL",
  "S44",
  "S17",
  "S24",
  "S38",
  "S62",
  "S35",
  "S39",
  "S60",
  "S20"
)
```

```{r TRX-data}
counts <- read_csv(
  "/Users/vilkal/work/Brolidens_work/Projects/Candida-omics/Tidy_data/Transcriptomics/Counts_all_trx_samples.csv"
) %>%
  select(ensembl, symbol)
TR_long <- TRX_batch %>%
  #rename(Metabolite="svamp_ID") %>%
  rownames_to_column(var = "feature") %>%
  pivot_longer(
    .,
    cols = -c("feature"),
    names_to = "sample",
    values_to = "abundance"
  ) %>%
  #filter(sample %in% s) %>%
  filter(abundance != 0) %>%
  left_join(
    .,
    select(
      meta,
      1:6,
      fct1_clus,
      `Clinical_score_(0-5)`,
      CST,
      group_longitudinal
    ),
    by = c("sample")
  )

group_df <- read_csv("../Results/Enrichment/Genes_clust.csv")
gene_col <- c(
  "#B71E42FF",
  "#DE478E",
  "#BC72F0FF",
  "#795FAFFF",
  "#D53DD0",
  "#EA6312",
  "#FFAE34FF",
  "#EF6F6AFF",
  "#8CC2CAFF",
  "#6388B4FF"
)

top_genes <- weights$Transcriptomics$feature[1:100]

pat_gr <- "/Users/vilkal/Library/CloudStorage/OneDrive-KI.SE/Svam Integration/svamp publicaions/Microbiome literature search.xlsx"
TRX_genes <- read_xlsx(pat_gr, sheet = "TRX links", na = "na") %>%
  left_join(
    .,
    rownames_to_column(weights$Transcriptomics, var = "order"),
    by = c("genes" = "feature")
  ) %>%
  mutate(factor = ifelse(is.na(.$factor), "non HVG", .$factor)) %>%
  left_join(., group_df, by = "genes") %>%
  mutate(clus = factor(.$clus)) %>%
  mutate(col = gene_col[as.integer(.$clus)]) %>%
  mutate(col = ifelse(is.na(.$col), "gray", .$col)) #%>%
#split(~factor)

setdiff(top_genes, TRX_genes$genes)
top_LM <- c(
  "LDHA",
  "PKM",
  "ACSL1",
  "CLEC7A",
  "CARD9",
  "EGFR",
  "DUSP1",
  "FOS",
  "TLR2",
  "TLR4",
  "DEFB4A,DEFB4B",
  "DEFB103B,DEFB103A",
  "IDO1",
  "MMP8",
  "G6PD",
  "CAD",
  "DHODH",
  "PANK1",
  "PANK2",
  "GLS",
  "GLUL",
  "FASN",
  "CHKA",
  "ETNK1"
)

top_genes <- unique(TRX_genes$genes)

TR_avg <- TR_long %>%
  filter(sample %in% s) %>%
  filter(feature %in% top_genes) %>%
  select(feature, abundance, fct1_clus) %>%
  #distinct() %>%
  summarise(
    Avg = mean(abundance),
    Avg_ = if_else(max(abundance) > 0, mean(abundance) / max(abundance), 0), # gives the median as a percentage of max value among spots if .5 youhave a  normal dist.
    Pct = sum(abundance > 0) / length(abundance) * 100,
    .by = c("fct1_clus", "feature")
  ) %>%
  filter(Avg != 0) #%>%
# nest(., .by = c("short", "long", "fct1_clus")) %>%
# mutate(n = map_int(data, ~ nrow(.x)), .before = "data") %>%
# arrange(long, fct1_clus)
```

```{r plot-top-genes}
#| fig.width: 5
#| fig.height: 7
# selected genes
top_top <- c(
  c("CARD9", "PANK2", "LDHA", "DEFB4A, DEFB4B", "DEFB103B,DEFB103A"),
  c(weights$Transcriptomics$feature[1:20]),
  c("IDO1", "PKM", "PANK1", "TLR4", "ACER1", "ACSL1")
)

## 1. Create ggplots and legends separately -------------------------------

plot_list <- TR_avg %>%
  left_join(select(TRX_genes, feature = genes, process, clus, col, factor)) %>%
  filter(factor == "1") %>%
  filter(feature %in% top_top) %>%
  split(.$process) %>%
  map(function(.x) {
    p <- ggplot(
      .x,
      aes(
        x = factor(fct1_clus),
        y = Avg,
        colour = feature,
        group = feature
      )
    ) +
      geom_line(linewidth = 1) +
      geom_point(size = 2) +
      scale_colour_manual(values = setNames(.x$col, .x$feature)) +
      labs(title = unique(.x$process)) +
      theme_bw() +
      theme(
        axis.title = element_blank(),
        plot.margin = margin(2, 2, 2, 2),
        plot.title = element_text(size = 8, vjust = -0.5),

        legend.position = "right",
        legend.title = element_blank(),
        legend.justification = c(0, .5),
        legend.box.just = "left",

        legend.margin = margin(0, 0, 0, 0),
        legend.box.margin = margin(0, 0, 0, 0),
        legend.box.spacing = unit(0, "cm"),
        legend.spacing.y = unit(0.05, "cm"),
        legend.key.height = unit(0.3, "cm"),
        legend.key.spacing.y = unit(0.05, "cm"),

        legend.text = element_text(
          size = 8,
          margin = margin(0, 0, 0, 1, "pt")
        )
      ) +
      guides(
        colour = guide_legend(
          keyheight = unit(.3, "cm"),
          keywidth = unit(.3, "cm"),
          byrow = TRUE,
          ncol = 1
        )
      )

    list(
      plot = p + theme(legend.position = "none"),
      legend = cowplot::get_legend(p)
    )
  })

## 2. Align all plotting panels ------------------------------------------

aligned_plots <- cowplot::align_plots(
  plotlist = map(plot_list, "plot"),
  align = "v",
  axis = "l"
)

## 3. Add legends back ----------------------------------------------------

plots <- map2(
  aligned_plots,
  map(plot_list, "legend"),
  ~ cowplot::plot_grid(
    .x,
    .y,
    nrow = 1,
    rel_widths = c(1, 0.5),
    align = "v",
    axis = "l"
  )
)

## 4. Final figure --------------------------------------------------------
# quartz(width = 5, height = 7, dpi = 100)
cowplot::plot_grid(
  plotlist = plots,
  ncol = 2,
  byrow = FALSE,
  align = "v",
  axis = "l"
)
```


```{r plot-rest-of-genes-of-intrest}
rest <- setdiff(top_genes, top_top)

TR_avg %>%
  filter(feature %in% rest) %>%
  left_join(
    .,
    select(TRX_genes, feature = "genes", process, clus, col, factor)
  ) %>%
  filter(factor == "non HVG") %>%
  ggplot(
    .,
    aes(
      x = factor(fct1_clus),
      y = Avg,
      color = feature,
      group = feature
    )
  ) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  #scale_colour_manual(values = setNames(TRX_genes$col, TRX_genes$genes)) +
  facet_wrap(
    ~process,
    scales = "free_y",
    ncol = 2
  ) +
  labs(
    x = "Cluster",
    y = "abundance",
    color = NULL
  ) +

  theme_bw() +
  theme(
    strip.background = element_blank(),
    legend.position = "right",
    legend.direction = "vertical",
    legend.spacing.y = unit(0.05, "cm"),
    legend.key.height = unit(0.3, "cm"),
    legend.margin = margin(0, 0, 0, 0),
    legend.box.margin = margin(0, 0, 0, 0)
  ) +
  guides(
    color = guide_legend(byrow = TRUE, ncol = 1),
    linetype = guide_legend(byrow = TRUE, ncol = 1)
  )
```

```{r Fluconazole-plot}

MB_path <- "../Results/MixOmic/Metabolom_Normalized_all.csv"
MB_matrix <- read_csv(MB_path)

MB_long <- MB_matrix %>%
  #rename(Metabolite="svamp_ID") %>%
  pivot_longer(
    .,
    cols = -c("Metabolite"),
    names_to = "sample",
    values_to = "abundance"
  ) %>%
  #filter(sample %in% s) %>%
  filter(abundance != 0) %>%
  left_join(
    .,
    select(
      meta,
      1:6,
      fct1_clus,
      `Clinical_score_(0-5)`,
      CST,
      group_longitudinal
    ),
    by = c("sample")
  )

# jitter object
jitterer <- position_jitter(width = 0.3, seed = 129)

var <- "CST"
var <- "RVVC_pos"
var <- "treatment"
df <- MB_long %>%
  #filter(sample %in% s) %>%
  mutate(treatment = str_extract(.$group_longitudinal, "FLZ|CHG")) %>%
  mutate(
    treatment = ifelse(
      is.na(.$group_longitudinal),
      "Crossectional",
      .$treatment
    )
  ) %>%
  mutate(timepoint = str_extract(.$sample, "1W|3M|6M")) %>%
  mutate(timepoint = ifelse(is.na(.$timepoint), "Baseline", .$timepoint))

add_jitter <- function(df, group, width = 0.25) {
  set.seed(123)
  df %>%
    mutate(
      group_num = as.numeric(factor({{ group }})),
      group_jit = group_num + runif(n(), -width, width)
    )
}

# quartz(width = 4, height = 4, dpi = 100)
jitterer <- position_jitter(width = 0.35, seed = 137) # 37
df %>%
  add_jitter(., "timepoint") %>%
  filter(Metabolite == "Fluconazole") %>%
  arrange(desc(abundance)) %>%
  #filter(Metabolite == "Ethanolamine") %>%
  ggplot(., aes(x = .data[["timepoint"]], y = abundance)) +
  ggtitle("Fluconazole") +
  geom_point(
    aes(fill = .data[[var]]),
    col = "gray",
    shape = 21,
    position = jitterer
  ) +
  geom_text(
    data = . %>% filter(abundance > 3),
    aes(label = sample),
    vjust = 1,
    hjust = -0.1,
    size = 1.5,
    position = jitterer
  ) +
  scale_fill_manual(values = pal[[var]]) +
  theme_minimal()
```

```{r MB-FM-integration}
#| include: false
# not used
links <- tribble(
  ~group                                                                                         , ~pathway , ~metabolite ,

  # Ethanolamine metabolism
  "Ethanolamine metabolism"                                                                      ,
  "ethanolamine utilization"                                                                     ,
  "Ethanolamine"                                                                                 ,

  # Host glycan / mucin degradation
  "Host glycan degradation"                                                                      ,
  "superpathway of N-acetylglucosamine, N-acetylmannosamine and N-acetylneuraminate degradation" ,
  "N-Acetylneuraminic Acid"                                                                      ,

  # Nucleotide metabolism
  "Nucleotide metabolism"                                                                        ,
  "inosine-5'-phosphate biosynthesis I"                                                          ,
  "Uracil"                                                                                       ,

  "Nucleotide metabolism"                                                                        ,
  "inosine-5'-phosphate biosynthesis II"                                                         ,
  "Uracil"                                                                                       ,

  "Nucleotide metabolism"                                                                        ,
  "superpathway of purine nucleotides de novo biosynthesis I"                                    ,
  "Uracil"                                                                                       ,

  "Nucleotide metabolism"                                                                        ,
  "superpathway of pyrimidine ribonucleotides de novo biosynthesis"                              ,
  "Uracil"                                                                                       ,

  # Pentose phosphate / sugar alcohol metabolism
  "Pentose phosphate metabolism"                                                                 ,
  "pentose phosphate pathway"                                                                    ,
  "Ribitol"                                                                                      ,

  "Pentose phosphate metabolism"                                                                 ,
  "pentose phosphate pathway"                                                                    ,
  "Arabitol"                                                                                     ,

  "Pentose phosphate metabolism"                                                                 ,
  "pentose phosphate pathway"                                                                    ,
  "Xylulose"                                                                                     ,

  # Glycolysis / carbon metabolism
  "Central carbon metabolism"                                                                    ,
  "glycolysis I (from glucose 6-phosphate)"                                                      ,
  "Fructose"                                                                                     ,

  "Central carbon metabolism"                                                                    ,
  "glycolysis I (from glucose 6-phosphate)"                                                      ,
  "Xylulose"                                                                                     ,

  "Central carbon metabolism"                                                                    ,
  "glycolysis I (from glucose 6-phosphate)"                                                      ,
  "Succinic acid"                                                                                ,

  "Central carbon metabolism"                                                                    ,
  "glycolysis I (from glucose 6-phosphate)"                                                      ,
  "Glycolic acid"                                                                                ,

  # Amino acid biosynthesis
  "Amino acid metabolism"                                                                        ,
  "superpathway of L-lysine, L-threonine and L-methionine biosynthesis II"                       ,
  "Isoleucine"                                                                                   ,

  "Amino acid metabolism"                                                                        ,
  "L-lysine biosynthesis II"                                                                     ,
  "Isoleucine"                                                                                   ,

  "Amino acid metabolism"                                                                        ,
  "L-lysine biosynthesis VI"                                                                     ,
  "Isoleucine"                                                                                   ,

  # Sulfur amino acid metabolism
  "Sulfur amino acid metabolism"                                                                 ,
  "L-cysteine biosynthesis VI (from L-methionine)"                                               ,
  "Hypotaurine"                                                                                  ,

  # Lipid and membrane metabolism
  "Membrane lipid metabolism"                                                                    ,
  "phosphatidylglycerol biosynthesis I (plastidic)"                                              ,
  "Linoleic acid"                                                                                ,

  "Membrane lipid metabolism"                                                                    ,
  "phosphatidylglycerol biosynthesis II (non-plastidic)"                                         ,
  "Linoleic acid"                                                                                ,

  "Membrane lipid metabolism"                                                                    ,
  "cis-vaccenate biosynthesis"                                                                   ,
  "Elaidic acid"                                                                                 ,

  # Cofactor metabolism
  "Coenzyme A metabolism"                                                                        ,
  "coenzyme A biosynthesis I (prokaryotic)"                                                      ,
  "Myo-Inositol 1-Monophosphate"                                                                 ,

  "Coenzyme A metabolism"                                                                        ,
  "superpathway of coenzyme A biosynthesis III (mammals)"                                        ,
  "Myo-Inositol 1-Monophosphate"
)
```

```{r prepp-combined-MB-FM}
#| fig.width: 7.3
#| fig.height: 8.5
pat_gr <- "/Users/vilkal/Library/CloudStorage/OneDrive-KI.SE/Svam Integration/svamp publicaions/Microbiome literature search.xlsx"
links <- read_xlsx(pat_gr, sheet = "Links", na = "na")

mb_means <- MB_long %>%
  filter(sample %in% s) %>%
  filter(Metabolite %in% links$metabolite) %>%
  group_by(fct1_clus, feature = Metabolite) %>%
  summarise(
    mean_abund = mean(abundance, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(type = "Metabolite")

func_means <- comb_long$community_lvl %>%
  filter(sample %in% s) %>%
  rename(feature = "long") %>%
  filter(feature %in% links$pathway) %>%
  group_by(fct1_clus, feature) %>%
  summarise(
    mean_abund = mean(abundance, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(type = "Pathway")

plot_df <- bind_rows(mb_means, func_means) %>%
  group_by(feature) %>%
  mutate(
    value_scaled = as.numeric(scale(mean_abund))
  ) %>%
  ungroup()

col_pal <- c(FM_colours, MB_colours)
plot_df <- plot_df %>%
  left_join(
    links %>%
      pivot_longer(
        c(pathway, metabolite),
        values_to = "feature"
      ) %>%
      select(group, group2, feature),
    by = "feature"
  ) %>%
  mutate(
    feature = ifelse(type == "Pathway", insert_line_break(.$feature), .$feature)
  ) %>%
  mutate(feature = factor(.$feature, levels = names(col_pal))) %>%
  mutate(group2 = factor(.$group2, levels = unique(links$group2)))
```

```{r plot-MB-FM}
#| fig.width: 9
#| fig.height: 10
library(cowplot)
library(purrr)

plots <- plot_df %>%
  split(.$group2) %>%
  map(function(.x) {
    p <- ggplot(
      .x,
      aes(
        x = factor(fct1_clus),
        y = value_scaled,
        colour = feature,
        group = feature
      )
    ) +
      geom_line(aes(linetype = type), linewidth = 1, show.legend = F) +
      geom_point(size = 2) +
      scale_colour_manual(values = col_pal) +
      labs(title = unique(.x$group2)) +
      theme_bw() +
      theme(
        plot.margin = unit(c(0.1, 0, 0.2, 0), "cm"),
        legend.position = "right",
        axis.title = element_blank(),
        strip.background = element_blank(),
        legend.title = element_blank(),
        legend.spacing.y = unit(0.05, "cm"),
        legend.key.height = unit(0.3, "cm"),
        legend.margin = margin(0, 0, 0, 0),
        legend.justification = c(0, 0.5), # left, center
        legend.box.just = "left",
        plot.title = element_text(size = 8, vjust = -0.5),
        legend.text = element_text(
          size = 8,
          margin = margin(r = 0.3, l = 0.3, unit = "pt")
        ),
        legend.box.spacing = unit(0, 'cm'),
        legend.key.spacing.y = unit(.1, 'cm'),
        legend.box.margin = margin(0, 0, 0, 0)
      ) +
      guides(
        colour = guide_legend(
          byrow = TRUE,
          ncol = 1,
          keyheight = unit(0.3, "cm"),
          keywidth = unit(0.3, "cm"),
          default.unit = "cm"
        ),
        linetype = guide_legend(
          keyheight = unit(0.3, "cm"),
          keywidth = unit(0.6, "cm"),
          default.unit = "cm"
        )
      )

    leg <- cowplot::get_legend(p)

    p <- p + theme(legend.position = "none")

    cowplot::plot_grid(
      p,
      leg,
      nrow = 1,
      axis = "l",
      rel_widths = c(0.8, 1) # <- fixed legend width
    )
  })

# quartz(width = 9.5, height = 10, dpi = 100)
cowplot::plot_grid(plotlist = plots, ncol = 2, byrow = F)
```



```{r old}
#| eval: false
#| code-fold: true
# old not in use
m <- read_csv("../Results/Sample_omic_table.csv")
s <- m$sample[m$at_least_two & m$all_BL]
top <- weights$Functional$feature[1:20]

top <- c(top, "glycolysis IV")
# plot pathways expressed by candida
df_ <- comb_relative_path %>%
  filter(level == "taxa_lvl") %>%
  #filter(!(grepl("UNINTEGRATED|UNMAPPED", .$`# Pathway`))) %>%
  separate(col = "Pathway", sep = "\\|", into = c("Pathway", "taxa")) %>%
  separate(col = "Pathway", sep = ": ", into = c("short", "long")) %>%
  mutate(taxa = ifelse(is.na(taxa), "total", taxa)) %>%
  mutate(taxa = gsub("^.+s__", "", .$taxa)) %>%

  filter(short != "UNINTEGRATED") %>%
  #filter(grepl("Candida", .$taxa)) %>%
  pivot_longer(
    .,
    cols = -c(level:taxa),
    names_to = "sample",
    values_to = "abundance"
  ) %>%
  filter(sample %in% s) %>%
  filter(abundance != 0) %>%
  left_join(
    .,
    select(meta, 1:6, fct1_clus, `Clinical_score_(0-5)`),
    by = c("sample")
  ) %>%

  # create species column
  mutate(species = str_replace_all(taxa, "_", " ")) %>%
  mutate(genus = str_replace(taxa, "_\\w+$", ""))
```

```{r check-taxa-contribution}
# look at the number of taxa that contribute to each pathway within each fct1 group
df_nest <- comb_long$taxa_lvl %>%
  filter(long %in% top) %>%
  select(short, long, genus, abundance, fct1_clus) %>%
  #distinct() %>%
  summarise(
    Avg = mean(abundance),
    Avg_ = if_else(max(abundance) > 0, mean(abundance) / max(abundance), 0), # gives the median as a percentage of max value among spots if .5 youhave a  normal dist.
    Pct = sum(abundance > 0) / length(abundance) * 100,
    .by = c("fct1_clus", "short", "long", "genus")
  ) %>%
  filter(Avg != 0) %>%
  nest(., .by = c("short", "long", "fct1_clus")) %>%
  mutate(n = map_int(data, ~ nrow(.x)), .before = "data") %>%
  arrange(long, fct1_clus)

print(df_nest, n = 28)
df_nest$data[[13]]
df_nest$data[[27]]
```

```{r taxa-contrib-abundance-plot}
#| fig.width: 7.3
#| fig.height: 8.5

df_filt <- comb_long$taxa_lvl %>%
  filter(long %in% c(top, "glycolysis IV")) %>%
  mutate(long = insert_line_break(long))

# col pal
extra <- c("#E3E6AD", "#F8D0A4", "#c4ce96", "#9aacce", "#e1caff", "#abc5bf")
tax_pallet <- c(brewer.pal(12, "Set3"), brewer.pal(8, "Dark2"), extra)

MG_hirarchy <- read_csv("../Results/Metagenomics/Metagenome_col_pal.csv")
MG_colours <- set_names(MG_hirarchy$col, MG_hirarchy$strain)
MG_colours <- MG_hirarchy %>%
  select(genus, col) %>%
  filter(row_number() == 1, .by = "genus") %>%
  deframe()

new <- setdiff(unique(df_filt$species), MG_hirarchy$species)
new <- setdiff(unique(df_filt$genus), MG_hirarchy$genus)

MG_colours <- set_names(
  c(MG_colours, c(tax_pallet[1:length(new)], "gray")),
  c(names(MG_colours), c(new, "other"))
)

# you can choose if you want to include species by sum abundance or by alfabetical
# dpending on if you use the levels() or just the order of n
n_lvl <- c(MG_hirarchy$genus %>% unique() %>% as.vector(), new)
n <- c(levels(MG_hirarchy$species)[1:20], new)

p <- df_filt %>%
  #mutate(species = factor(species, levels = c(n_lvl, "unclassified"))) %>%
  mutate(sample = factor(sample, levels = sample_order)) %>%
  mutate(genus = factor(genus, levels = c(n_lvl))) %>%
  Facet_bar.fun(
    df = ., #mutate(df, sample = forcats::fct_relevel(sample, sample_order)),
    facet_cols = "fct1_clus",
    fill = "genus",
    colours = MG_colours,
    strip_colours = c("#a4d19b", "#d5edbe", "#ffc99e", "#ffe3c1"),
    x_axis = "sample",
    annot_col = "Clinical_score_(0-5)", #"RVVC_pos",
    legend = "bottom"
  )
p

p <- df_filt %>%
  #mutate(species = factor(species, levels = c(n_lvl, "unclassified"))) %>%
  mutate(sample = factor(sample, levels = sample_order)) %>%
  mutate(genus = factor(genus, levels = c(n_lvl))) %>%
  Facet_bar.fun(
    df = ., #mutate(df, sample = forcats::fct_relevel(sample, sample_order)),
    facet_cols = "fct1_clus",
    facet_rows = "long",
    fill = "genus",
    colours = MG_colours,
    strip_colours = c("#a4d19b", "#d5edbe", "#ffc99e", "#ffe3c1"),
    x_axis = "fct1_clus",
    #annot_col = "Clinical_score_(0-5)", #"RVVC_pos",
    legend = "bottom"
  )

# add CLR
p <- p %>% add_CLR(df_filt, x = "fct1_clus")

legend <- get_legend(p)
p <- p +
  scale_y_continuous(
    breaks = c(1),
    labels = scales::label_percent(scale = 100)
  ) +
  theme(
    legend.position = "none",
    strip.text.y.right = element_text(angle = 0, hjust = 0, size = 9)
  )

# quartz(width = 7.3, height = 8.5, dpi = 100)
plot <- plot_grid(
  p,
  legend,
  ncol = 1,
  rel_heights = c(1, 0.16)
)
plot
```

